### ISSUE TITLE
Publish on Metadata

### ISSUE THREAD

**Issue by vchuravy** [andrewcooke/IntModN.jl#1]
Hej Andrew,

I was wondering if you would be interested in pushing `IntModN` to Metadata so that it gets a bit more exposure?

**Comment by andrewcooke** [comment]
hi.  thanks for the interest.  sure, i can do that, but it looks like it needs some work to get running on 0.3 (build currently failing).  at the end of this month i change to working 50% time (yay!) and so i'll look at this then (second week in may, since the first week i am actually working).  sorry i can't do it quicker, but i am pretty busy.  cheers, andrew

**Comment by andrewcooke** [comment]
hi - this should now be available.  it's not building on 0.4 dues to some bug (in julia afaict), but is fine in 0.3.

**Comment by andrewcooke** [comment]
the bug for reference - https://github.com/JuliaLang/julia/issues/11271

**Comment by andrewcooke** [comment]
and now this works in 0.4 (as well as 0.3)

**Comment by vchuravy** [comment]
Thanks for this :)
